Neos:
  Media:
    assetSources:
      giphy:
        assetSource: 'Webandco\Giphy\AssetSource\GiphyAssetSource'
        assetSourceOptions:
          icon: 'resource://Webandco.Giphy/Public/Giphy.svg'
          apiKey: ''
          copyrightNoticeTemplate: '${"Photo by <a href=\"" + user.profile_url + "\">" + user.display_name + "</a> on <a href=\"https://giphy.com\">Giphy</a>"}'

