Neos:
  Media:
    assetSources:
      giphy:
        assetSource: 'Webco\Giphy\AssetSource\GiphyAssetSource'
        assetSourceOptions:
          icon: 'resource://Webco.Giphy/Public/Giphy.svg'
          apiKey: ''
          copyrightNoticeTemplate: '${"Photo by <a href=\"" + user.profileUrl + "\">" + user.displayName + "</a> on <a href=\"https://giphy.com\">Giphy</a>"}'

